kind: Kustomization

resources:
- deployment-frontend.yaml
- deployment.yaml
- service.yaml
- service-frontend.yaml

mkdir -p overlays/{apac,emea}

kind: Kustomization

bases:
  - ../../base

nameSuffix: -apac

kubectl kustomize overlays/apac/

git remote set-url origin git@github.com:alfiilham03/DO480-apps.git

git remote add origin https://[TOKEN]@github.com/alfiilham03/DO480-apps.git

images:
 - name: mysql
   newName: registry.redhat.io/rhel8/mysql-80
   newTag: 1-152

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.ocp4.example.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-apac
    weight: 100
  wildcardPolicy: None


kind: Kustomization

bases:
  - ../../base
resources:
nameSuffix: -emea

images:
 - name: mysql
   newName: registry.redhat.io/rhel8/mysql-80
   newTag: 1-156


apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.ocp4-mng.example.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-emea
    weight: 100
  wildcardPolicy: None


resources:
- route-mng.yaml


oc create secret generic \
   --from-file config.yaml=./config.yaml \
   --from-file ldap.crt=./ldap.crt init-config-bundle-secret \
   -n registry

podman push localhost/budget-app:development \
  central-quay-registry.apps.ocp4.example.com/finance/budget-app-dev
  
FROM registry.access.redhat.com/ubi8/httpd-24:1
RUN echo hello >/var/www/html/index.html
