kind: Kustomization

resources:
- deployment-frontend.yaml
- deployment.yaml
- service.yaml
- service-frontend.yaml

mkdir -p overlays/{apac,emea}

kind: Kustomization

bases:
  - ../../base

nameSuffix: -apac

kubectl kustomize overlays/apac/

git remote set-url origin git@github.com:alfiilham03/DO480-apps.git

git remote add origin https://[TOKEN]@github.com/alfiilham03/DO480-apps.git
