kind: Kustomization

resources:
- deployment-frontend.yaml
- deployment.yaml
- service.yaml
- service-frontend.yaml

mkdir -p overlays/{apac,emea}

kind: Kustomization

bases:
  - ../../base

nameSuffix: -apac

kubectl kustomize overlays/apac/

git remote set-url origin git@github.com:alfiilham03/DO480-apps.git

git remote add origin https://[TOKEN]@github.com/alfiilham03/DO480-apps.git

images:
 - name: mysql
   newName: registry.redhat.io/rhel8/mysql-80
   newTag: 1-152

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.ocp4.example.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-apac
    weight: 100
  wildcardPolicy: None
